apiVersion: v1
kind: Namespace
metadata:
  name: curl-ns
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl-sa
  namespace: curl-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-deploy
  namespace: curl-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
      version: 1.0.0
  template:
    metadata:
      labels:
        app: curl
        version: 1.0.0
    spec:
      serviceAccountName: curl-sa
      containers:
      - name: curl-co
        image: curlimages/curl
        command:
        - /bin/sh
        - -c
        - while curl --no-progress-meter http://httpbin.org/uuid; do sleep 0.2; done;
