apiVersion: v1
kind: Namespace
metadata:
  name: httpbin-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin-sa
  namespace: httpbin-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httbin-deploy
  namespace: httpbin-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: 1.0.0
  template:
    metadata:
      labels:
        app: httpbin
        version: 1.0.0
    spec:
      serviceAccountName: httpbin-sa
      containers:
      - name: httpbin-co
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
